# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imageEditor.ui'
#
# Created: Thu Oct 22 20:35:48 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1000, 1000)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.toolBar = QtGui.QGroupBox(self.centralwidget)
        self.toolBar.setGeometry(QtCore.QRect(0, 0, 50, 1000))
        self.toolBar.setTitle(_fromUtf8(""))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        self.Brush = QtGui.QPushButton(self.toolBar)
        self.Brush.setGeometry(QtCore.QRect(0, 60, 50, 50))
        self.Brush.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Images/paintbrush.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Brush.setIcon(icon)
        self.Brush.setIconSize(QtCore.QSize(35, 35))
        self.Brush.setCheckable(False)
        self.Brush.setAutoDefault(False)
        self.Brush.setDefault(False)
        self.Brush.setFlat(False)
        self.Brush.setObjectName(_fromUtf8("Brush"))
        self.Rectangle = QtGui.QPushButton(self.toolBar)
        self.Rectangle.setGeometry(QtCore.QRect(0, 180, 50, 50))
        self.Rectangle.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Images/rectangle.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Rectangle.setIcon(icon1)
        self.Rectangle.setIconSize(QtCore.QSize(35, 35))
        self.Rectangle.setObjectName(_fromUtf8("Rectangle"))
        self.BlackRec = QtGui.QPushButton(self.toolBar)
        self.BlackRec.setGeometry(QtCore.QRect(0, 400, 45, 35))
        self.BlackRec.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("Images/blackRec.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BlackRec.setIcon(icon2)
        self.BlackRec.setIconSize(QtCore.QSize(45, 45))
        self.BlackRec.setObjectName(_fromUtf8("BlackRec"))
        self.LineLinker = QtGui.QPushButton(self.toolBar)
        self.LineLinker.setGeometry(QtCore.QRect(0, 120, 50, 50))
        self.LineLinker.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("Images/diagLine.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LineLinker.setIcon(icon3)
        self.LineLinker.setIconSize(QtCore.QSize(35, 35))
        self.LineLinker.setObjectName(_fromUtf8("LineLinker"))
        self.Bucket = QtGui.QPushButton(self.toolBar)
        self.Bucket.setGeometry(QtCore.QRect(0, 240, 50, 50))
        self.Bucket.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("Images/bucket.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Bucket.setIcon(icon4)
        self.Bucket.setIconSize(QtCore.QSize(35, 35))
        self.Bucket.setObjectName(_fromUtf8("Bucket"))
        self.Eraser = QtGui.QPushButton(self.toolBar)
        self.Eraser.setGeometry(QtCore.QRect(0, 300, 50, 50))
        self.Eraser.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("Images/eraser.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Eraser.setIcon(icon5)
        self.Eraser.setIconSize(QtCore.QSize(35, 35))
        self.Eraser.setObjectName(_fromUtf8("Eraser"))
        self.WhiteRec = QtGui.QPushButton(self.toolBar)
        self.WhiteRec.setGeometry(QtCore.QRect(0, 460, 45, 35))
        self.WhiteRec.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("Images/whiteRec.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.WhiteRec.setIcon(icon6)
        self.WhiteRec.setIconSize(QtCore.QSize(45, 45))
        self.WhiteRec.setObjectName(_fromUtf8("WhiteRec"))
        self.RedRec = QtGui.QPushButton(self.toolBar)
        self.RedRec.setGeometry(QtCore.QRect(0, 520, 45, 35))
        self.RedRec.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("Images/redRec.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RedRec.setIcon(icon7)
        self.RedRec.setIconSize(QtCore.QSize(45, 45))
        self.RedRec.setObjectName(_fromUtf8("RedRec"))
        self.abrir = QtGui.QPushButton(self.toolBar)
        self.abrir.setGeometry(QtCore.QRect(0, 590, 41, 27))
        self.abrir.setObjectName(_fromUtf8("abrir"))
        self.sair = QtGui.QPushButton(self.toolBar)
        self.sair.setGeometry(QtCore.QRect(0, 670, 41, 27))
        self.sair.setObjectName(_fromUtf8("sair"))
        self.salvar = QtGui.QPushButton(self.toolBar)
        self.salvar.setGeometry(QtCore.QRect(0, 630, 41, 27))
        self.salvar.setObjectName(_fromUtf8("salvar"))
        self.deletar = QtGui.QPushButton(self.toolBar)
        self.deletar.setGeometry(QtCore.QRect(0, 710, 41, 27))
        self.deletar.setObjectName(_fromUtf8("deletar"))
        self.binarizar = QtGui.QPushButton(self.toolBar)
        self.binarizar.setGeometry(QtCore.QRect(0, 750, 41, 27))
        self.binarizar.setObjectName(_fromUtf8("binarizar"))
        self.undo_ = QtGui.QPushButton(self.toolBar)
        self.undo_.setGeometry(QtCore.QRect(0, 790, 41, 27))
        self.undo_.setObjectName(_fromUtf8("undo_"))
        self.ampliar = QtGui.QPushButton(self.toolBar)
        self.ampliar.setGeometry(QtCore.QRect(0, 830, 41, 27))
        self.ampliar.setObjectName(_fromUtf8("ampliar"))
        self.reduzir = QtGui.QPushButton(self.toolBar)
        self.reduzir.setGeometry(QtCore.QRect(0, 870, 41, 27))
        self.reduzir.setObjectName(_fromUtf8("reduzir"))
        self.original = QtGui.QPushButton(self.toolBar)
        self.original.setGeometry(QtCore.QRect(0, 910, 41, 27))
        self.original.setObjectName(_fromUtf8("original"))
        self.PrimaryBar = QtGui.QSlider(self.centralwidget)
        self.PrimaryBar.setGeometry(QtCore.QRect(190, 10, 160, 29))
        self.PrimaryBar.setMaximum(255)
        self.PrimaryBar.setSliderPosition(150)
        self.PrimaryBar.setOrientation(QtCore.Qt.Horizontal)
        self.PrimaryBar.setTickPosition(QtGui.QSlider.TicksBelow)
        self.PrimaryBar.setObjectName(_fromUtf8("PrimaryBar"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 111, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.PrimaryValue = QtGui.QLineEdit(self.centralwidget)
        self.PrimaryValue.setGeometry(QtCore.QRect(140, 10, 41, 27))
        self.PrimaryValue.setObjectName(_fromUtf8("PrimaryValue"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(360, 20, 121, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.SecondaryBar = QtGui.QSlider(self.centralwidget)
        self.SecondaryBar.setGeometry(QtCore.QRect(540, 10, 160, 29))
        self.SecondaryBar.setMaximum(255)
        self.SecondaryBar.setSliderPosition(255)
        self.SecondaryBar.setOrientation(QtCore.Qt.Horizontal)
        self.SecondaryBar.setTickPosition(QtGui.QSlider.TicksBelow)
        self.SecondaryBar.setObjectName(_fromUtf8("SecondaryBar"))
        self.SecondaryValue = QtGui.QLineEdit(self.centralwidget)
        self.SecondaryValue.setGeometry(QtCore.QRect(490, 10, 41, 27))
        self.SecondaryValue.setObjectName(_fromUtf8("SecondaryValue"))
        self.SecondaryActivate = QtGui.QCheckBox(self.centralwidget)
        self.SecondaryActivate.setGeometry(QtCore.QRect(700, 10, 21, 22))
        self.SecondaryActivate.setText(_fromUtf8(""))
        self.SecondaryActivate.setChecked(False)
        self.SecondaryActivate.setTristate(False)
        self.SecondaryActivate.setObjectName(_fromUtf8("SecondaryActivate"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(740, 20, 131, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.AutoDetectToggle = QtGui.QCheckBox(self.centralwidget)
        self.AutoDetectToggle.setGeometry(QtCore.QRect(880, 10, 21, 22))
        self.AutoDetectToggle.setText(_fromUtf8(""))
        self.AutoDetectToggle.setChecked(True)
        self.AutoDetectToggle.setTristate(False)
        self.AutoDetectToggle.setObjectName(_fromUtf8("AutoDetectToggle"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArquivo = QtGui.QMenu(self.menubar)
        self.menuArquivo.setObjectName(_fromUtf8("menuArquivo"))
        self.menuSobre = QtGui.QMenu(self.menubar)
        self.menuSobre.setObjectName(_fromUtf8("menuSobre"))
        self.menuEditar = QtGui.QMenu(self.menubar)
        self.menuEditar.setObjectName(_fromUtf8("menuEditar"))
        self.menuReduzir = QtGui.QMenu(self.menuEditar)
        self.menuReduzir.setObjectName(_fromUtf8("menuReduzir"))
        MainWindow.setMenuBar(self.menubar)
        self.menuArquivo.addSeparator()
        self.menuEditar.addAction(self.menuReduzir.menuAction())
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuEditar.menuAction())
        self.menubar.addAction(self.menuSobre.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.abrir.setText(_translate("MainWindow", "Abrir", None))
        self.abrir.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.sair.setText(_translate("MainWindow", "Sair", None))
        self.sair.setShortcut(_translate("MainWindow", "Ctrl+D", None))
        self.salvar.setText(_translate("MainWindow", "Salvar", None))
        self.salvar.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.deletar.setText(_translate("MainWindow", "Del", None))
        self.deletar.setShortcut(_translate("MainWindow", "Ctrl+L", None))
        self.binarizar.setText(_translate("MainWindow", "Bin", None))
        self.binarizar.setShortcut(_translate("MainWindow", "Ctrl+B", None))
        self.undo_.setText(_translate("MainWindow", "Undo", None))
        self.undo_.setShortcut(_translate("MainWindow", "Ctrl+Z", None))
        self.ampliar.setText(_translate("MainWindow", "Amp", None))
        self.ampliar.setShortcut(_translate("MainWindow", "Ctrl+=", None))
        self.reduzir.setText(_translate("MainWindow", "Red", None))
        self.reduzir.setShortcut(_translate("MainWindow", "Ctrl+-", None))
        self.original.setText(_translate("MainWindow", "Orig", None))
        self.original.setShortcut(_translate("MainWindow", "Ctrl+R", None))
        self.label.setText(_translate("MainWindow", "Limite Primário", None))
        self.PrimaryValue.setText(_translate("MainWindow", "150", None))
        self.label_2.setText(_translate("MainWindow", "Limite Secundário", None))
        self.SecondaryValue.setText(_translate("MainWindow", "255", None))
        self.label_3.setText(_translate("MainWindow", "Detecção do Crânio", None))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo", None))
        self.menuSobre.setTitle(_translate("MainWindow", "Sobre", None))
        self.menuEditar.setTitle(_translate("MainWindow", "Editar", None))
        self.menuReduzir.setTitle(_translate("MainWindow", "Reduzir...", None))

